# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='\u0627\u0633\u0645 \u0627\u0644\u0628\u0644\u0648\u0643 ')),
                ('cover', models.FileField(blank=True, null=True, upload_to='covers')),
                ('is_clinical', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='\u0627\u0633\u0645 \u0627\u0644\u0643\u062a\u0627\u0628')),
                ('description', models.TextField(blank=True, help_text='\u0627\u062e\u062a\u064a\u0627\u0631\u064a', verbose_name='\u0648\u0635\u0641 \u0627\u0644\u0643\u062a\u0627\u0628')),
                ('cover', models.FileField(blank=True, null=True, upload_to='covers')),
                ('download', models.CharField(blank=True, help_text='\u0627\u062e\u062a\u064a\u0627\u0631\u064a', max_length=250, verbose_name='\u0631\u0627\u0628\u0637 \u0627\u0644\u062a\u062d\u0645\u064a\u0644')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0631\u0641\u0639')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_contributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('M', '\u0643\u0644\u064a\u0629 \u0627\u0644\u0637\u0628'), ('A', '\u0643\u0644\u064a\u0629 \u0627\u0644\u0639\u0644\u0648\u0645 \u0627\u0644\u0637\u0628\u064a\u0629 \u0627\u0644\u062a\u0637\u0628\u064a\u0642\u064a\u0629'), ('P', '\u0643\u0644\u064a\u0629 \u0627\u0644\u0635\u064a\u062f\u0644\u0629'), ('D', '\u0643\u0644\u064a\u0629 \u0637\u0628 \u0627\u0644\u0623\u0633\u0646\u0627\u0646'), ('B', '\u0643\u0644\u064a\u0629 \u0627\u0644\u0639\u0644\u0648\u0645 \u0648 \u0627\u0644\u0645\u0647\u0646 \u0627\u0644\u0635\u062d\u064a\u0629'), ('N', '\u0643\u0644\u064a\u0629 \u0627\u0644\u062a\u0645\u0631\u064a\u0636'), ('I', ' \u0643\u0644\u064a\u0629 \u0627\u0644\u0635\u062d\u0629 \u0627\u0644\u0639\u0627\u0645\u0629 \u0648\u0627\u0644\u0645\u0639\u0644\u0648\u0645\u0627\u062a\u064a\u0629 \u0627\u0644\u0635\u062d\u064a\u0629')], max_length=1, verbose_name='\u0627\u0644\u0627\u0633\u0645')),
                ('city', models.CharField(choices=[('R', '\u0627\u0644\u0631\u064a\u0627\u0636'), ('J', '\u062c\u062f\u0629'), ('A', '\u0627\u0644\u0623\u062d\u0633\u0627\u0621')], max_length=1, verbose_name='\u0627\u0644\u0645\u062f\u064a\u0646\u0629')),
                ('gender', models.CharField(choices=[('F', '\u0637\u0627\u0644\u0628\u0627\u062a'), ('M', '\u0637\u0644\u0627\u0628')], max_length=1, verbose_name='\u0627\u0644\u062c\u0646\u0633')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='\u0627\u062e\u062a\u064a\u0627\u0631\u064a', verbose_name='\u0648\u0635\u0641 \u0627\u0644\u062a\u0642\u064a\u064a\u0645')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u0636\u0627\u0641\u0629')),
                ('rating', models.CharField(choices=[('5', '5 Stars out of 5'), ('4', '4 Stars out of 5'), ('3', '3 Stars out of 5'), ('2', '2 Stars out of 5'), ('1', '1 Stars out of 5')], max_length=1)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.Book')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student', models.BooleanField(default=True, verbose_name='\u0637\u0627\u0644\u0628\u061f')),
                ('ar_first_name', models.CharField(max_length=30, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0623\u0648\u0644')),
                ('ar_last_name', models.CharField(max_length=30, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0623\u062e\u064a\u0631')),
                ('en_first_name', models.CharField(max_length=30, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0623\u0648\u0644')),
                ('en_last_name', models.CharField(max_length=30, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0623\u062e\u064a\u0631')),
                ('city', models.CharField(choices=[('R', '\u0627\u0644\u0631\u064a\u0627\u0636'), ('J', '\u062c\u062f\u0629'), ('A', '\u0627\u0644\u0623\u062d\u0633\u0627\u0621')], max_length=1, verbose_name='\u0627\u0644\u0645\u062f\u064a\u0646\u0629')),
                ('gender', models.CharField(blank=True, choices=[('F', '\u0637\u0627\u0644\u0628\u0627\u062a'), ('M', '\u0637\u0644\u0627\u0628')], default='', max_length=1, verbose_name='\u0627\u0644\u062c\u0646\u0633')),
                ('university', models.CharField(choices=[('KHS', '\u062c\u0627\u0645\u0639\u0629 \u0627\u0644\u0645\u0644\u0643 \u0633\u0639\u0648\u062f \u0628\u0646 \u0639\u0628\u062f\u0627\u0644\u0639\u0632\u064a\u0632 \u0644\u0644\u0639\u0644\u0648\u0645 \u0627\u0644\u0635\u062d\u064a\u0629'), ('KFU', '\u062c\u0627\u0645\u0639\u0629 \u0627\u0644\u0645\u0644\u0643 \u0641\u064a\u0635\u0644'), ('KSAU', '\u062c\u0627\u0645\u0639\u0629 \u0627\u0644\u0645\u0644\u0643 \u0633\u0639\u0648\u062f'), ('PSU', '\u062c\u0627\u0645\u0639\u0629 \u0627\u0644\u0623\u0645\u064a\u0631 \u0633\u0644\u0637\u0627\u0646'), ('KSU', '\u062c\u0627\u0645\u0639\u0629 \u0627\u0644\u0645\u0644\u0643 \u0633\u0644\u0645\u0627\u0646 \u0627\u0644\u062e\u0631\u062c')], max_length=1, verbose_name='\u0627\u0644\u062c\u0627\u0645\u0639\u0629')),
                ('batch', models.PositiveSmallIntegerField(verbose_name='\u0627\u0644\u062f\u0641\u0639\u0629')),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='profile_pics')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blocks.College', verbose_name='\u0627\u0644\u0643\u0644\u064a\u0629')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
