# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='is_clinical',
            field=models.BooleanField(verbose_name='is the block clinical?'),
        ),
    ]
