# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_auto_20161026_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
