# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_auto_20161028_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(blank=True, default='http://www.danieladorno.com/wp-content/uploads/2014/04/Empty_book_cover.png', max_length=1000, verbose_name='\u063a\u0644\u0627\u0641 \u0627\u0644\u0643\u062a\u0627\u0628'),
        ),
    ]
