# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_auto_20161029_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to=b'', verbose_name='\u0635\u0648\u0631\u0629 \u0627\u0644\u0643\u062a\u0627\u0628'),
        ),
    ]
