# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0007_add_blocks_and_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='is_clinical',
            field=models.BooleanField(default=False, verbose_name='is the block clinical?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(null=True, upload_to=b'', verbose_name='\u0635\u0648\u0631\u0629 \u0627\u0644\u062a\u0635\u0646\u064a\u0641'),
        ),
    ]
