# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 15:46
from __future__ import unicode_literals

from django.db import migrations

def add_blocks (apps, schema_editor):
    Block = apps.get_model('blocks','Block')
    if not Block.objects.exists():
        Block.objects.create(title='Foundation Block')
        Block.objects.create(title='Musculoskeletal Block')
        Block.objects.create(title='Respiratory Block')
        Block.objects.create(title='Hematology Block')
        Block.objects.create(title='Cardiovascular Block')
        Block.objects.create(title='Neurosciences Block')
        Block.objects.create(title='Endocrine Block')
        Block.objects.create(title='Urology and Renal Block')
        Block.objects.create(title='Gastroenterology Block')
        Block.objects.create(title='Oncology Block')
        Block.objects.create(title='EBM Block')
        Block.objects.create(title='Family Medicine Block',
                             is_clinical=True)
        Block.objects.create(title='Medicine Block',
                             is_clinical=True)
        Block.objects.create(title='Pediatric Block',
                             is_clinical=True
                             )
        Block.objects.create(title='Surgery Block',
                             is_clinical=True
                             )
        Block.objects.create(title='Obstetrics and Gynecology Block',
                             is_clinical=True
                             )
        Block.objects.create(title='Special Sense & Mental Health Block Book',
                             is_clinical=True
                             )
class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_auto_20161126_1828'),
    ]

    operations = [migrations.RunPython(add_blocks
                                       )
    ]
