# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0009_add_blocks_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='block',
            field=models.ManyToManyField(blank=True, null=True, to='blocks.Block'),
        ),
    ]
