# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0010_category_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='block',
            field=models.ManyToManyField(blank=True, help_text='\u0627\u062e\u062a\u064a\u0627\u0631\u064a', to='blocks.Block'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='\u0627\u062e\u062a\u064a\u0627\u0631\u064a', to='blocks.Category'),
        ),
    ]
