# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0011_auto_20161130_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='block',
            field=models.ManyToManyField(blank=True, to='blocks.Block'),
        ),
    ]
