# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0012_auto_20161201_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='block',
            field=models.ManyToManyField(blank=True, default='block.id', to='blocks.Block'),
        ),
    ]
